CREATE TABLE anime(
       ID INTEGER PRIMARY NOT NULL AUTOINCREMENT,
       NAME TEXT NOT NULL,
       EPISODE TEXT NOT NULL,
       STATUS TEXT NOT NULL);

CREATE TABLE manga(
       ID INTEGER PRIMARY NOT NULL AUTOINCREMENT,
       NAME TEXT NOT NULL,
       CHAPTER TEXT NOT NULL,
       STATUS TEXT NOT NULL);

